import Header from "@/components/header";
import { TodoContextProvider } from "@/context";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <TodoContextProvider>
          <header>
            <Header />
          </header>
          <div
            style={{
              display: "flex",
              flexWrap: "wrap",
              margin: "auto",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            {children}
          </div>
        </TodoContextProvider>
      </body>
    </html>
  );
}
